def decrypt(text):
    for i in range(1, 27):
        result = ""
        for j in range(len(text)):
            result += chr((ord(text[j]) + i) % 26 + 65)
        print("Key: " + str(i) + " Plain-Text: " + result)

text = "YOAXLAQKQGPTVWQCQXXSRXJGTQYORCRNAKQKGVNWUQRTXOQBGYVLACBTQRYWAXBVXYKGJJRRCWSRNFQWGPPYOQWGTJGVXQPQNNRXNQQLACXYRCYNDKGJJRRCWCQAYOQTGPYOQGYOQTXYGGFYOQNQRXYCGYAKQGPOQTBGACBKGJJRYOGVBOXOQNGGFQWURKFGCKQGTYSAKQKGJJRORNPOGLACBYORYYOQDSGVNWKRNNRPYQTOQTYOQNRXYYAJQXOQXRSYOQJKGJJRYOQDSQTQYTDACBYGLVYYOQWGTJGVXQACYGYOQYQRLGYWGYRYRCDTRYQANNCQMQTBGYOQTQRBRACXRAWRNAKQRXXOQLAKFQWOQTSRDYOTGVBOYOQSGGWWGYAYXYOQXYVLAWQXYYQRLRTYDAQMQTSRXRYACRNNJDNAPQHVXYRXXOQXRAWYOAXKGJJRXOQCGYAKQWYORYGCQGPYOQYTQQXORWRWGGTNQRWACBTABOYACYGAY"

